### ISSUE TITLE
Editor styling

### ISSUE THREAD

**Issue by dartiss** [ArrayHQ/atomic-blocks-theme#14]
I believe, apologies if I'm wrong, that you've added styling to the Gutenberg editor so that it looks more like the front-end. However, I've used the customizer controls to modify the front-end sizes and now the editor changes make it look less consistent. Can the editor styling be in step with any customizer changes?

**Comment by mikemcalister** [comment]
Hi David, 

We should be able to do that. Which styles are you referring to specifically?

**Comment by dartiss** [comment]
Certainly the heading is way out-of-whack with how I've defined it. So, I've reduced the default size down using the customizer slider but in GB it's still the default, larger size. I'm assuming the same issue will affect the body text as well.

**Comment by mikemcalister** [comment]
Hi David, 

I've just released version 1.1.6 of the theme, which brings header font size, body font size, and accent colors from the Customizer to the block editor. Go ahead and check it out and let me know how it works for you!

**Comment by dartiss** [comment]
That's spot on Mike - many thanks for this.

**Comment by boyettcamp** [comment]
I am having a similar(ish) issue I think? Please excuse I am a novice!..
I love this Theme's simplicity and I am trying force myself to use Gutenberg and move away from the 'old school' in favour of the New World Order!...
In the Theme - Customiser - I increased the width of the content area about +30% greater than your Demo. However, the Gutenberg Editor remains very narrow and does not reflect the 'Preview Mode' result. Even in 'Widescreen Mode' the Gutenberg Editor is very narrow and this is annoying when I am trying to get the layout of Pages/Posts looking nice. Please help. I would be very, very grateful if I could get my Gutenberg Editor to better reflect what will actually be displayed. I really like this theme and dearly wish to continue to use it. Thanks guys. Andrew.
