### ISSUE TITLE
sticky header menu

### ISSUE THREAD

**Issue by cfoellmann** [ArrayHQ/atomic-blocks-theme#15]
I dont know how to describe it nicely.
It would be great if the menu in the header would have the same behaviour as the `Latest` theme.

**Comment by dartiss** [comment]
So, an option to make the header sticky? I really like that idea and would second it, as it's an annoyance when the menu isn't available as the visitor is partly scrolled down.

**Comment by donini** [comment]
And since the Block let us create rich content, sometimes the scroll is huge to go back to the main menu. Good idea @cfoellmann!

**Comment by mikemcalister** [comment]
Going to leave this feature up to custom implementations.
