### ISSUE TITLE
so how about a simple child theme?

### ISSUE THREAD

**Issue by overcatbe** [ArrayHQ/atomic-blocks-theme#17]
[atomic-child.zip](https://github.com/ArrayHQ/atomic-blocks-theme/files/2343046/atomic-child.zip)

**Comment by mikemcalister** [comment]
Thanks for this! We also have a child theme available on our Array site.

**Comment by firelite** [comment]
@overcatbe I tried out your child theme and was wondering if there's a particular reason you've added all those lines into style.css?
