### ISSUE TITLE
Bug: lists are displaying in incorrect font

### ISSUE THREAD

**Issue by dartiss** [ArrayHQ/atomic-blocks-theme#22]
This is a continuation of #20, as 1.2.2 has not resolved this issue.

Here is a screenshot from a post I just put together, demonstrating the issue...

<img width="937" alt="screenshot 2018-09-27 at 07 25 38" src="https://user-images.githubusercontent.com/14928971/46126922-d2718180-c226-11e8-98ef-f27fbb04967f.png">

**Comment by mikemcalister** [comment]
This has been fixed along the way. Sorry we didn't close the ticket sooner!
