### ISSUE TITLE
Grid Columns not fully working logged out

### ISSUE THREAD

**Issue by quicoto** [ArrayHQ/atomic-blocks-theme#27]
Hello,

WordPress:  4.9.8
Guttenberg: 4.4.0
Atomic Blocks Theme 1.2.3

I have this blog post https://www.ricardtorres.com/rant/whatsapp-finally-has-stickers/ which when I'm logged in it looks ok (2 columns for images) but if you're logged out you don't see the 2 columns.

Definitely the CSS is different in the different scenarios. Not sure why. Are the styles coming from the Theme or Gutenberg?

Thank you.

## Logged in
![](https://cloudup.com/cuMSolnIZgo+)

## Logged out
![](https://cloudup.com/c2NMMZUMAE4+)

**Comment by mikemcalister** [comment]
Hi there,

I've tested this in the latest version of Atomic Blocks with no issues. I see no issues between logged in and logged out. The theme doesn't have any kind of conditional CSS loading like that so it may be a local issue.
