### ISSUE TITLE
Cover image not working

### ISSUE THREAD

**Issue by quicoto** [ArrayHQ/atomic-blocks-theme#28]
WordPress 4.9.8
Gutenberg 4.4.0
Theme 1.2.3

When using the Cover block in Gutenberg it seems the theme doesn't have those styles. Or are only printed when I'm logged in.

You can clearly see from the screenshots below how there are missing CSS properties ( example URL https://www.ricardtorres.com/review/horsing-around-red-dead-redemption-2/ )

The HTML generated in the Preview looks like:

```
<div class="wp-block-cover has-parallax alignfull" style="background-image:url(https://www.ricardtorres.com/wp-content/uploads/2018/11/xRed-Dead-Redemption-2-ps4-2.jpg.pagespeed.ic.BhAx2ORiNO.webp)"></div>
```

## Logged in
![Logged in](https://cloudup.com/cV82_5nkgvr+)

## Anonymous 
![Logged in](https://cloudup.com/cKcp7gezwNN+)

Thank you in advance

**Comment by quicoto** [comment]
So, what I've found that is not being loaded when not logged in is this:

`/wp-content/plugins/gutenberg/build/block-library/style.css`

I did install the Gutenberg plugin additionally to be in WordPress 5.0.1 because I want the new updates.

Still, not sure sure it's not included.

**Comment by mikemcalister** [comment]
Hi there, 

The cover image seems to be working fine on my end in 1.2.4. Update should be coming soon to wp.org.
