### ISSUE TITLE
Jetpack 'like' button not displaying correctly

### ISSUE THREAD

**Issue by dartiss** [ArrayHQ/atomic-blocks-theme#3]
When using the Jetpack 'Like' option along with their Share buttons, the Like button appears on the same line, which it shouldn't do. It's using an H3 wrapper.

Here is a screenshot...

<img width="589" alt="screen shot 2018-07-19 at 17 15 04" src="https://user-images.githubusercontent.com/14928971/42957663-4601c2f0-8b7b-11e8-9ac7-d7db3db34ed6.png">

**Comment by mikemcalister** [comment]
Hi David, 

We just released a fix for this in version 1.1.4. Thanks for the report!

**Comment by dartiss** [comment]
Brilliant - thanks. Have tried this now and can confirm that it's fixed.
