### ISSUE TITLE
Box shadow causes double underline in AB Post Grid block

### ISSUE THREAD

**Issue by mindctrl** [ArrayHQ/atomic-blocks-theme#36]
If you set a custom accent color in the theme, it adds a box shadow to links. This causes the links in the Post Grid block to have an underline and a box shadow. Originally reported here: https://github.com/studiopress/atomic-blocks/issues/81

**Comment by mikemcalister** [comment]
Looks like this was fixed along the way. I'm testing now and not able to reproduce. Looks like there are styles in place to prevent the box shadow.
