### ISSUE TITLE
Add display swap to Google font

### ISSUE THREAD

**Issue by quicoto** [ArrayHQ/atomic-blocks-theme#38]
The theme could add the `&display=swap` query argument to improve the performance on the First Meaningful Paint.

https://addyosmani.com/blog/google-fonts-font-display/

I assume simply adding it here would do

https://github.com/ArrayHQ/atomic-blocks-theme/blob/master/functions.php#L170

On my personal blog https://ricard.blog/ I've overwritten the function in my child theme to use display swap and I went from 3 seconds to 1.7 seconds on First Meaningful Paint, giving it 4 extra points to Google PageSpeed Insights.

**Could you consider it?**

Thank you in advance

**Comment by mindctrl** [comment]
@quicoto thanks for the suggestion! We'll have it added in the next update.
