### ISSUE TITLE
Comment avatars overlapping

### ISSUE THREAD

**Issue by dartiss** [ArrayHQ/atomic-blocks-theme#4]
I'm finding that Gravatars on comments are overlapping. I'm using the Jetpack comment options but not sure if this includes the comment output, or just the adding of new ones.

Here is a screenshot of it...

<img width="822" alt="screen shot 2018-07-19 at 17 14 46" src="https://user-images.githubusercontent.com/14928971/42957852-c00ffd1e-8b7b-11e8-8108-d9918bcb4ddd.png">

**Comment by mikemcalister** [comment]
Hey David, 

Do you have a live link I can look at for this? I'm not getting the same thing on my end.

**Comment by dartiss** [comment]
Hi Mike. I'd switched out the theme whilst the various issues were being resolved. However, it's now active and you can see it here - https://artiss.blog/2018/04/embedding-code-in-your-wordpress-posts/

**Comment by mikemcalister** [comment]
Thanks for sending that over, David! Can you do a quick test for me and turn off Lazy Loading images in Jetpack? I have a feeling that might have something to do with it. If that's it, I'll see what kind of fixes we can find for that.

**Comment by mikemcalister** [comment]
Hey David, never mind that last request. I found a fix for the comment avatars, which has just been released in version 1.1.5.

**Comment by dartiss** [comment]
You're amazing - thanks Mike.
