### ISSUE TITLE
Jetpack related posts are displaying oddly

### ISSUE THREAD

**Issue by dartiss** [ArrayHQ/atomic-blocks-theme#5]
Here is how related posts show using my old theme, and how I would expect them to show...

<img width="724" alt="screen shot 2018-07-19 at 17 17 28" src="https://user-images.githubusercontent.com/14928971/42957967-154c7974-8b7c-11e8-9181-ed199b08e89e.png">

However, with the Atomic Blocks theme, it's displaying like this...

<img width="911" alt="screen shot 2018-07-19 at 17 16 44" src="https://user-images.githubusercontent.com/14928971/42957984-20564fac-8b7c-11e8-98fa-e5dccbfd50dc.png">

Excerpts are displaying instead of the post title. Now show how this can be theme related but I'm not sure how else this is displaying in this way.

**Comment by mikemcalister** [comment]
Hi David, 

We just released a fix for this in version 1.1.4. Thanks for the report!

**Comment by dartiss** [comment]
Brilliant - thanks. Have tried this now and can confirm that it's fixed.
