### ISSUE TITLE
Enhancements: Minor header improvements

### ISSUE THREAD

**Issue by dartiss** [ArrayHQ/atomic-blocks-theme#7]
It would be really nice to have the following tweaks to the current theme...

1. Specify the colour of the header section. I've done it using CSS but a colour-picker, as per the other options, would be a lot better.
2. Rather than have just the text OR a header that's just an image, would it be possible to have a third option - both. So, a graphic can be uploaded and displayed to the left of the text?

**Comment by donini** [comment]
Yep, same here!

**Comment by mikemcalister** [comment]
Hi David, 

Thanks for the thoughts here. 

1. This would be a nice addition. However, something to consider is that adding a header background color would also require adding color options for header text color, header link color, menu item color, etc. Changing the background color would potentially make these hard to read, so you would need adjustments for those as well. 

I'm not opposed to adding these, but in terms of priority, these features will likely come later on.

2. There are also some implications here to consider. Usually, it's not as simple as uploading an image and adding text to the right. Logo dimensions vary greatly and getting the text to vertically align with variable-sized logos can be difficult to manage from the theme. There are also mobile implications of how to style this and ensure the logo and text are always vertically aligned. 

This is probably best handled by adding the text to the image instead. That way, you can control how the text and image looks consistently on all devices.
