### ISSUE TITLE
AB Testimonials issue

### ISSUE THREAD

**Issue by marcusig** [ArrayHQ/atomic-blocks-theme#8]
Hi, 
Here's the issue I reported on [wp.org:](https://wordpress.org/support/topic/bug-testimonial-block-error/#post-10527748)

![screen capture - ab testimonials](https://user-images.githubusercontent.com/11990914/43222171-a8e91eda-904f-11e8-9239-cdab6fd506e5.gif)

**Comment by mikemcalister** [comment]
Thanks for the detailed report, Marcus! I'll take a closer look at this and get an update out.

**Comment by mikemcalister** [comment]
This bug was fixed in version 1.2.7 of the Atomic Blocks plugin. Thanks again for the report!
