### ISSUE TITLE
Comment avatars overlapping 

### ISSUE THREAD

**Issue by dartiss** [ArrayHQ/atomic-blocks-theme#9]
Apologies for this but I can't re-open #4. 

Even after updating to 1.1.5 this is still occurring - please see https://artiss.blog/2018/04/embedding-code-in-your-wordpress-posts/

**Comment by mikemcalister** [comment]
Hi David, 

I wonder if there was some browser caching going on, because the avatars [look good on my end](https://cl.ly/tQLo). Can you confirm? Try a few hard refreshes to see if that helps.

**Comment by dartiss** [comment]
You're right - it's now cleared (odd, as I wiped the cache after the theme update). I'll close this now. Thanks.
